{% set name = "WaterNetworkAnalysis" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 0f4458b3f2c8f066e0c8a5436a0fd1e585e94041e80fc70469eb1d142139e97a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - conservedwatersearch >=0.1.0
    - mdanalysis >=2.4.0
    - numpy >=1.22
    - scipy >=1.0.0
    - python-wget

test:
  imports:
    - WaterNetworkAnalysis
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JecaTosovic/WaterNetworkAnalysis
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://WaterNetworkAnalysis.readthedocs.io/
  dev_url: https://github.com/JecaTosovic/WaterNetworkAnalysis
  summary: Preparation of input and analysis of output for ConservedWaterSearch.

extra:
  recipe-maintainers:
    - JecaTosovic
    - DomFijan
