{% set name = "WaterNetworkAnalysis" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/WaterNetworkAnalysis-{{ version }}.tar.gz
  sha256: 8b805ac2ff1d6d431a07fe7d47829ba45118a45c3dc10e7b56d458c0ecd09cf0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - conservedwatersearch >=0.1.0
    - mdanalysis >=2.4.0
    - numpy >=1.22
    - scipy >=1.0.0
    - python-wget

test:
  imports:
    - WaterNetworkAnalysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JecaTosovic/WaterNetworkAnalysis
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://WaterNetworkAnalysis.readthedocs.io/
  dev_url: https://github.com/JecaTosovic/WaterNetworkAnalysis
  summary: Preparation of input and analysis of output for ConservedWaterSearch.

extra:
  recipe-maintainers:
    - JecaTosovic
    - DomFijan
