{% set name = "WaterNetworkAnalysis" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/WaterNetworkAnalysis-{{ version }}.tar.gz
  sha256: ba4f48adcd144511fe3cc7984e574e24e307d2ae317e0d62a98b33959a8b8042

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - conservedwatersearch >=0.1.0
    - mdanalysis >=2.4.0
    - numpy >=1.22
    - scipy >=1.0.0
    - python-wget

test:
  imports:
    - WaterNetworkAnalysis
  requires:
    - pip
    - python {{ python_min }}
    - wget
  commands:
    - pip check

about:
  home: https://github.com/JecaTosovic/WaterNetworkAnalysis
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://WaterNetworkAnalysis.readthedocs.io/
  dev_url: https://github.com/JecaTosovic/WaterNetworkAnalysis
  summary: Preparation of input and analysis of output for ConservedWaterSearch.

extra:
  recipe-maintainers:
    - JecaTosovic
    - DomFijan
