{% set name = "WaterNetworkAnalysis" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/WaterNetworkAnalysis-{{ version }}.tar.gz
  sha256: ac115117df181f965cf23ce65c30265373049c70888e95b9ea0b405670d23a71

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - conservedwatersearch
    - mdanalysis
    - numpy <1.24
    - python-wget

test:
  imports:
    - WaterNetworkAnalysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JecaTosovic/WaterNetworkAnalysis
  license: GPL-2.0-or-later
  license_file: LICENSE
  doc_url: https://WaterNetworkAnalysis.readthedocs.io/
  dev_url: https://github.com/JecaTosovic/WaterNetworkAnalysis
  summary: Preparation of input and analysis of output for ConservedWaterSearch.

extra:
  recipe-maintainers:
    - JecaTosovic
    - DomFijan
